### ISSUE TITLE
No magic numbers

### ISSUE THREAD

**Issue by incredibleLeitman** [CapioIM/NumberGuessing#1]
https://github.com/CapioIM/NumberGuessing/blob/bb7a7a0ee20b076b8eae0bab4eed389f68c8c77e/NumberGuessing/Program.cs#L29

If you use a hardcoded number that defines the behavior of your program, this should be a constant ☝️ 
Same applies for the number of tried

**Comment by CapioIM** [comment]
Number of tries varies so variable cannot be constant ?

**Comment by incredibleLeitman** [comment]
yes, changing variables cannot be const, but the initial value can be :D

You have:
```
int triesLeft = 5;              // number of attempts

for (int i = 0; i <= 5; i++)
```
which both use a hardcoded 5 that should be a constant
