### ISSUE TITLE
Remove unnecessary file from repo

### ISSUE THREAD

**Issue by incredibleLeitman** [CapioIM/NumberGuessing#2]
The folder ".vs", "obj" and "build/debug/bin" (or release depending what you build) are generated everytime when you compile your program, so they are not needed to be in the repository.

You can delete those, commit the removing to git and push
and the next time they appear on the changes list, add them to the gitignore file

Maybe if you want to provide am executable of your program to github, you can use the "Releases" tab :D

**Comment by CapioIM** [comment]
gotcha
