### ISSUE TITLE
This will generate a number between 1 and 99

### ISSUE THREAD

**Issue by incredibleLeitman** [CapioIM/NumberGuessing#3]
https://github.com/CapioIM/NumberGuessing/blob/bb7a7a0ee20b076b8eae0bab4eed389f68c8c77e/NumberGuessing/Program.cs#L26

Whereas in your introduction you print that the number is between 1 and 100.
Besides this missmatch, if you use the same number multiple times in your code *and* it defines the behaviour of your program it should be a constant

**Comment by CapioIM** [comment]
when I put rng.Next(0, 101) , actually at some point random number was 0 , so I initially understood that numbers from and till are inclusive of those numbers. and returned back to (1,100).
Changed to (1,101)

**Comment by incredibleLeitman** [comment]
the documentation states that ```A 32-bit signed integer greater than or equal to minValue and less than maxValue; that is, the range of return values includes minValue but not maxValue```
https://learn.microsoft.com/en-us/dotnet/api/system.random.next?view=net-7.0#system-random-next(system-int32-system-int32)

Don't assume anything 👆 Either read the documentation or verify it by yourself 😏
