### ISSUE TITLE
Change return to break

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/NumberGuessing#8]
https://github.com/CapioIM/NumberGuessing/blob/1e2e91a1fb6a3c2a9911015977145d8de2ca9244/NumberGuessing/Program.cs#L82

Here you should rather use an break instead of return.
It will end up doing the same in your code here, but makes a big difference later on.

return --> jumps out of the whole method you are currently in. So here it would be jumping out of your Main() method and stop program
break --> will just break/stop the loop you are currently in. So for example, if you have two nested loops, you would just stop the loop you are currently in.

```
for (int i =0;i<=10;i++)
{
   for (j = 1;j<20;j++)
  {
     if (i==2)
    {
      break;
    }
  }
  // after break will jump here in outer loop, and will not leave whole program!
}
```

**Comment by CapioIM** [comment]
isn't break going to jump out of nested for loop to 1st line for loop ?

**Comment by CapioIM** [comment]
changed return to break
